const DESTINATIONS = [
  "Ahrensfelde Friedhof",
  "Ahrensfelde Nord",
  "Alt Hüttendorf",
  "Alt Rosenthal",
  "Altdöbern",
  "Altes Lager",
  "Altranft",
  "Angermünde",
  "Babelsberg",
  "Bad Belzig",
  "Bad Freienwalde (Oder)",
  "Bad Liebenwerda",
  "Bad Saarow",
  "Bad Saarow Klinikum",
  "Bad Wilsnack",
  "Bagenz",
  "Bahnsdorf",
  "Baitz",
  "Bärenklau",
  "Baruth (Mark)",
  "Basdorf",
  "Beelitz-Heilstätten",
  "Beelitz Stadt",
  "Beeskow",
  "Beetz-Sommerfeld",
  "Bergfelde (b Berlin)",
  "Bergsdorf",
  "Berkenbrück",
  "Bernau (b Berlin)",
  "Bernau-Friedenstal",
  "Bestensee",
  "Beutersitz",
  "Biesenthal",
  "Birkengrund",
  "Birkenstein",
  "Birkenwerder (b Berlin)",
  "Blankenfelde (Kr Teltow-Fläming)",
  "Blönsdorf",
  "Blumberg (b Berlin)",
  "Blumberg-Rehhahn",
  "Blumenthal (Mark)",
  "Bölzke",
  "Borgsdorf",
  "Borkheide",
  "Brand (Niederlausitz)",
  "Brandenburg-Altstadt",
  "Brandenburg Hbf",
  "Breddin",
  "Brieselang",
  "Briesen (Mark)",
  "Britz",
  "Brück (Mark)",
  "Brügge (Prign)",
  "Buchholz (Zauche)",
  "Buckow (b Beeskow)",
  "Buschow",
  "Calau (Niederlausitz)",
  "Caputh-Geltow",
  "Caputh-Schwielowsee",
  "Casekow",
  "Chorin",
  "Coschen",
  "Cottbus Hbf",
  "Cottbus-Merzdorf",
  "Cottbus-Sandow",
  "Cottbus-Willmersdorf Nord",
  "Dabendorf",
  "Dahlewitz",
  "Dallgow-Döberitz",
  "Dannenwalde (Kr Gransee)",
  "Döberitz",
  "Doberlug-Kirchhain",
  "Dossow (Prign)",
  "Drahnsdorf",
  "Drebkau",
  "Eberswalde Hbf",
  "Eichwalde",
  "Eisenhüttenstadt",
  "Elsholz",
  "Elstal",
  "Elsterwerda",
  "Elsterwerda-Biehla",
  "Erkner",
  "Falkenberg (Elster)",
  "Falkenberg (Mark)",
  "Falkenhagen Gewerbepark Prignitz",
  "Falkensee",
  "Fangschleuse",
  "Ferch-Lienewitz",
  "Fermerswalde",
  "Finkenheerd",
  "Finkenkrug",
  "Finsterwalde (Niederlausitz)",
  "Flughafen BER – Terminal 1-2",
  "Flughafen BER – Terminal 5 (Schönefeld)",
  "Fohrde",
  "Forst (Lausitz)",
  "Frankfurt (Oder)",
  "Frankfurt (Oder)-Neuberesinchen",
  "Frankfurt (Oder)-Rosengarten",
  "Fredersdorf (b Berlin)",
  "Fretzdorf",
  "Friedersdorf (b Königs Wusterhausen)",
  "Friesack (Mark)",
  "Fürstenberg (Havel)",
  "Fürstenwalde (Spree)",
  "Fürstenwalde (Spree) Süd",
  "Glöwen",
  "Gollmitz (Niederlausitz)",
  "Golm",
  "Golßen (Niederlausitz)",
  "Golzow (b Eberswalde)",
  "Golzow (Oderbruch)",
  "Görden",
  "Gorgast",
  "Götz",
  "Gransee",
  "Griebnitzsee",
  "Groß Köris",
  "Groß Kreutz",
  "Groß Pankow",
  "Groß Schönebeck (Schorfheide)",
  "Großbeeren",
  "Großräschen",
  "Großwudicke",
  "Grüneberg",
  "Grunow (Niederlausitz)",
  "Guben",
  "Halbe",
  "Hammelspring",
  "Hangelsberg",
  "Hegermühle",
  "Heiligengrabe",
  "Helenesee",
  "Hennigsdorf (b Berlin)",
  "Herrensee",
  "Herzberg (Elster) West",
  "Herzberg (Mark)",
  "Hohen Neuendorf (b Berlin)",
  "Hohen Neuendorf West",
  "Hohenleipisch",
  "Hoppegarten (Mark)",
  "Hosena",
  "Hubertushöhe",
  "Jänschwalde",
  "Jänschwalde Ost",
  "Joachimsthal",
  "Joachimsthal Kaiserbahnhof",
  "Jüterbog",
  "Kablow",
  "Karstädt",
  "Kerkwitz",
  "Kirchmöser",
  "Klandorf",
  "Klasdorf",
  "Klinge",
  "Klosterfelde",
  "Kolkwitz",
  "Kolkwitz Süd",
  "Königs Wusterhausen",
  "Kraftwerk Finkenheerd",
  "Kremmen",
  "Kummersdorf (b Storkow)",
  "Kunersdorf",
  "Küstrin-Kietz",
  "Kyritz",
  "Kyritz Am Bürgerpark",
  "Lauchhammer",
  "Lehnitz",
  "Letschin",
  "Leuthen (b Cottbus)",
  "Liebenthal (Prign)",
  "Lindenberg (Mark)",
  "Lindow (Mark)",
  "Lottschesee",
  "Löwenberg (Mark)",
  "Lübben (Spreewald)",
  "Lübbenau (Spreewald)",
  "Lubolz",
  "Luckaitztal",
  "Luckau-Uckro",
  "Luckenwalde",
  "Ludwigsfelde",
  "Mahlow",
  "Marquardt",
  "Medewitz (Mark)",
  "Melchow",
  "Meyenburg",
  "Michendorf",
  "Mixdorf",
  "Mögelin",
  "Mühlenbeck-Mönchmühle",
  "Müllrose",
  "Müncheberg (Mark)",
  "Nassenheide",
  "Nauen",
  "Nechlin",
  "Nennhausen",
  "Netzeband",
  "Neuenhagen (b Berlin)",
  "Neuhausen (b Cottbus)",
  "Neuhof (b Zossen)",
  "Neupetershain",
  "Neuruppin Rheinsberger Tor",
  "Neuruppin West",
  "Neustadt (Dosse)",
  "Neutrebbin",
  "Neuzelle",
  "Niederfinow",
  "Niedergörsdorf",
  "Niederlehme",
  "Obersdorf",
  "Oderin",
  "Oegeln",
  "Oehna",
  "Oranienburg",
  "Ortrand",
  "Passow (Uckermark)",
  "Paulinenaue",
  "Peitz Ost",
  "Perleberg",
  "Petershagen (Uckermark)",
  "Petershagen Nord",
  "Pillgram",
  "Pinnow (Uckermark)",
  "Plessa",
  "Potsdam Charlottenhof",
  "Potsdam Hbf",
  "Potsdam Medienstadt Babelsberg",
  "Potsdam Park Sanssouci",
  "Potsdam Pirschheide",
  "Potsdam-Rehbrücke",
  "Premnitz Nord",
  "Premnitz Zentrum",
  "Prenzlau",
  "Priort",
  "Pritzerbe",
  "Pritzwalk",
  "Pritzwalk Hainholz",
  "Pritzwalk West",
  "Prösen",
  "Prösen Ost",
  "Prösen West",
  "Raddusch",
  "Rangsdorf",
  "Rathenow",
  "Rehfeld (b Falkenberg/Elster)",
  "Rehfelde",
  "Rheinsberg (Mark)",
  "Röntgental",
  "Rosenwinkel",
  "Rückersdorf (Niederlausitz)",
  "Rüdnitz",
  "Ruhland",
  "Ruhlsdorf-Zerpenschleuse",
  "Saarmund",
  "Sachsenhausen (Nordb)",
  "Sarnow",
  "Schmachtenhagen",
  "Schneeberg (Mark)",
  "Schönborn (b Doberlug)",
  "Schönerlinde",
  "Schönfließ",
  "Schönfließ Dorf",
  "Schönow (Uckermark)",
  "Schönwalde (Barnim)",
  "Schönwalde (Spreewald)",
  "Schwante",
  "Schwarzheide Ost",
  "Schwedt (Oder)",
  "Schwedt (Oder) Mitte",
  "Seddin",
  "Sedlitz Ost",
  "Seefeld (Mark)",
  "Seegefeld",
  "Seehausen (Uckermark)",
  "Seelow (Mark)",
  "Seelow-Gusow",
  "Senftenberg",
  "Spremberg",
  "Storkow (Mark)",
  "Strausberg",
  "Strausberg Nord",
  "Strausberg Stadt",
  "Tantow",
  "Teichland",
  "Teltow",
  "Teltow Stadt",
  "Templin",
  "Templin Stadt",
  "Thyrow",
  "Trebbin",
  "Trebnitz (Mark)",
  "Treuenbrietzen",
  "Treuenbrietzen Süd",
  "Uebigau",
  "Vehlefanz",
  "Velten (Mark)",
  "Vetschau",
  "Vogelsang (Kr Gransee)",
  "Walddrehna",
  "Walsleben",
  "Wandlitz",
  "Wandlitzsee",
  "Warnitz (Uckermark)",
  "Waßmannsdorf",
  "Weisen",
  "Wellmitz",
  "Wendisch-Rietz",
  "Wensickendorf",
  "Werbig",
  "Werder (Havel)",
  "Werneuchen",
  "Wiesenau",
  "Wiesenburg (Mark)",
  "Wildau",
  "Wilhelmshorst",
  "Wilmersdorf (b Angermünde)",
  "Wittenberge",
  "Wittstock (Dosse)",
  "Woltersdorf (b Luckenwalde)",
  "Wriezen",
  "Wünsdorf Waldstadt",
  "Wusterhausen (Dosse)",
  "Wustermark",
  "Wusterwitz",
  "Wustrau-Radensleben",
  "Wutike",
  "Zeesen",
  "Zehdenick (Mark)",
  "Zellendorf",
  "Zehdenick-Neuhof",
  "Zepernick (b Bernau)",
  "Zernsdorf",
  "Zeuthen",
  "Ziltendorf",
  "Zossen",
  "Zühlsdorf",
];

const destinationText = document.querySelector("#destination");

function shuffle(array) {
  return array.slice().sort(() => Math.random() - 0.5);
}

function newDestination() {
  const shuffledDestinations = shuffle(DESTINATIONS);

  let i = 0;
  let counter = 10;
  let myFunction = function () {
    counter *= 1.2;
    destinationText.innerHTML = shuffledDestinations[i]
    i++
    if (i > 22) return
    setTimeout(myFunction, counter);
  };
  setTimeout(myFunction, counter);
}